# Generated by Django 5.2.14 on 2026-05-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
