# Generated by Django 5.2.14 on 2026-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_client_id_alter_empresa_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_contabilidade',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
