# Generated by Django 5.2.14 on 2026-05-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_email_contabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_pfx',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_senha',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
