# Generated by Django 5.2.14 on 2026-05-21 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('tipo', models.CharField(choices=[('NF', 'Nota Fiscal'), ('NFCE', 'Nota Fiscal de Consumidor Eletrônica'), ('CT', 'Conhecimento de Transporte'), ('MDFE', 'Manifesto de Documentos')], max_length=4)),
                ('numero_nota', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('autorizado', 'Autorizado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('caminho_arquivo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='empresas.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
