# Generated by Django 5.2.14 on 2026-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('NFe', 'Nota Fiscal Eletrônica'), ('NFCe', 'Nota Fiscal de Consumidor Eletrônica'), ('CTe', 'Conhecimento de Transporte Eletrônico'), ('MDFe', 'Manifesto de Documentos Fiscais Eletrônico')], max_length=4),
        ),
    ]
