# Generated by Django 5.2.14 on 2026-05-28 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('ncm', models.CharField(blank=True, max_length=20, null=True)),
                ('cest', models.CharField(blank=True, max_length=20, null=True)),
                ('cfop', models.CharField(blank=True, max_length=10, null=True)),
                ('cst_icms', models.CharField(blank=True, max_length=10, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=10, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='documentos.documento')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
    ]
