# Generated by Django 5.2.14 on 2026-05-31 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_itemdocumento'),
        ('empresas', '0004_empresa_certificado_pfx_empresa_certificado_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdocumento',
            name='empresa',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='itens_documentos_empresa', to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
