# Generated by Django 5.2.14 on 2026-05-31 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_itemdocumento_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-data_emissao', '-id']},
        ),
    ]
