# Generated by Django 5.2.14 on 2026-05-31 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_documento_options'),
        ('empresas', '0004_empresa_certificado_pfx_empresa_certificado_senha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacaoXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('label_periodo', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportacoes', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
